<?php
    $_product = $this->getProduct();
    $_helper  = $this->helper('catalog/output');
	$colorbox = Mage::helper('colorbox');
?>
<?php if(Mage::getStoreConfig('colorbox/settings/jquery') == 'google'): ?>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<?php endif; ?>

<?php if(Mage::getStoreConfig('colorbox/settings/jquery') == 'local'): ?>
	<script src="<?php echo $this->getSkinUrl('colorbox/jquery.min.js'); ?>"></script>
<?php endif; ?>

<script src="<?php echo $this->getSkinUrl('colorbox/jquery.colorbox.js'); ?>" type="text/javascript"></script>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('colorbox/'. Mage::getStoreConfig('colorbox/settings/theme') .'/colorbox.css'); ?>" type="text/css" media="screen" />
<script>
	jQuery.noConflict();
	jQuery(document).ready(function(){
			jQuery(".colorbox").colorbox(
				{
					rel:'colorbox',
					current: "<?php echo Mage::helper('colorbox')->__('Image {current} of {total}') ?>",
					previous: "<?php echo Mage::helper('colorbox')->__('previous') ?>",
					next: "<?php echo Mage::helper('colorbox')->__('next') ?>",
					close: "<?php echo Mage::helper('colorbox')->__('close') ?>"					      
				}
		);
	});
</script>
	
<p class="product-image">
    <a id="productimagemain" class="colorbox" href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($colorbox->getPopupSize()); ?>">
        <?php
            $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($colorbox->getMainSize()).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
            echo $_helper->productAttribute($_product, $_img, 'image');
        ?>
    </a>     
</p>

<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>
    <ul> 
    <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
        <li>
            <a class="colorbox" href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($colorbox->getPopupSize()); ?>"  title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($colorbox->getThumbSize()); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
            </a>
        </li>
    	<?php $i++ ?>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>

